name: docker-manifest-test
description: 'Tiny, simple GitHub Action to link Docker manifests easily'
author: 'carry0987'
branding:
    icon: target
    color: blue
runs:
    using: node24
    main: ./build/index.js
inputs:
    inputs:
        required: true
        description: >-
            A list of Docker images that were built from `docker build` to be the inputs
            into the merged manifests.

            Optionally, it can be comma-separated to create multiple final images from the
            given `images`.
    tags:
        description: A comma-separated list of tags that will be applied into the merged manifest from `inputs`.
        required: true
    push:
        description: Whether if the action should push the outputs to the Docker registry. Ignored if using `buildx imagetools`
        required: false
        default: 'false'
    fallback:
        description: Whether if this action should fallback to `manifest create`.
        required: false
        default: 'false'
    annotations:
        required: false
        default: ''
        description: >-
            A mapping of annotations to annotate the final, merged manifest.

            View the [`docker buildx imagetools create --annotation`](https://docs.docker.com/reference/cli/docker/buildx/imagetools/create/#annotation)
            documentation on how to format each annotation.
    append:
        required: false
        default: 'false'
        description: Sets the `--append` flag, which will add new sources to existing manifests.
    builder:
        required: false
        default: ''
        description: Sets the `--builder` for the `buildx` command.
outputs:
    images:
        description: A comma-separated list of images that were pushed.
